[package]
name = "ev3differ"
version = "0.1.1"
edition = "2024"

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.27", features = ["derive"] }
git2 = "0.20.0"
regex = "1.11.1"
walkdir = "2.5.0"
zip = "2.2.2"
