[package]
name = "ev3differ"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
git2 = "0.20.0"
walkdir = "2.5.0"
zip = "2.2.2"
zip-extensions = "0.8.1"
zip-extract = "0.2.1"
